// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://hkdepadvitvcfiprzypp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZGVwYWR2aXR2Y2ZpcHJ6eXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDMxMzMsImV4cCI6MjA1NTgxOTEzM30.3X7VsKXUegmSvI2S9hp3PSsXzpBMHsPq01uDsSIaDvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
